plugins { id 'com.android.application' }
android {
    namespace 'com.micro.enviarpc'
    compileSdk 34
    defaultConfig {
        applicationId "com.micro.enviarpc"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes { release { minifyEnabled false } }
}
